# Use containers
sudo: false

language: rust

rust:
  - nightly
  - beta
  - stable

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

before_script:
  - pip install 'travis-cargo' --user
  - export PATH=$HOME/.local/bin:$PATH

script:
  - travis-cargo build
  - travis-cargo test

after_success:
  - travis-cargo coveralls --no-sudo

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly